# Generated by Django 6.0.6 on 2026-06-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChessGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=64, unique=True)),
                ('white_player', models.CharField(blank=True, max_length=120)),
                ('black_player', models.CharField(blank=True, max_length=120)),
                ('board_fen', models.CharField(max_length=256)),
                ('turn', models.CharField(max_length=1)),
                ('status', models.CharField(default='waiting', max_length=120)),
                ('last_move', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
